#! /bin/bash

#################################################
# Header
#################################################
echo "<HTML>" >/tmp/ServUsg.html
echo "    <Head><Title>Hurd Server List and Usage</TITLE></HEAD>" >>/tmp/ServUsg.html
echo "    <BODY>" >>/tmp/ServUsg.html
echo "    <h2>Hurd Server List and Usage</h2>" >>/tmp/ServUsg.html
echo "<P><b>Note:</b> Contents is automatically generated via <code>ServUsg.sh</code>, don't edit it!" >>/tmp/ServUsg.html 
echo "" >>/tmp/ServUsg.html;

echo "    <h3><a href=\"http://140.120.7.20/KVM-tool/HurdAndMinix3-Via-Kvm.html#RandSer\">Random Server Example</a></h3>" >>/tmp/ServUsg.html

echo "<P><b>Note:</b> For security reason, <b>ssh</b> encapsulates " >>/tmp/ServUsg.html 
echo "your input.  Before it can do so, it needs a random number " >>/tmp/ServUsg.html  
echo "generated by random number server. We must install a random" >>/tmp/ServUsg.html  
echo "number server before configuring <b>sshd</b>: ssh daemon." >>/tmp/ServUsg.html 
echo "" >>/tmp/ServUsg.html 
echo "    <h3><a href=\"http://www.bddebian.com/~hurd-web/hurd/translator/examples/\">Translator Examples</a></h3>" >>/tmp/ServUsg.html
echo "" >>/tmp/ServUsg.html 

echo "    <h3>Hurd Server List</h3>" >>/tmp/ServUsg.html

echo "    <TABLE>" >>/tmp/ServUsg.html

declare -i i=1;

for serv in `ls /hurd`;   
  do 

    echo $serv | grep \\.sh$ 
    
    if [ $? -eq 0 ] 
      then echo "Skip Shell Script $serv" 
           continue
    fi

    if [ $i -eq 1 ]
      then echo "        <TR><TD><a href=\"#${serv}\">/hurd/${serv}</a>&nbsp;&nbsp;"\
 >>/tmp/ServUsg.html
    else echo "            <TD><a href=\"#${serv}\">/hurd/${serv}</a>&nbsp;&nbsp;"\
 >>/tmp/ServUsg.html
    fi
    ((i++));
    if [ $i -eq 5 ]
      then i=1;
    fi
  done
echo "    </TABLE>" >>/tmp/ServUsg.html
echo "" >>/tmp/ServUsg.html 

echo "    <h3>Hurd Server Usage</h3>" >>/tmp/ServUsg.html

for serv in `ls /hurd`;   
  do 
    echo "    <a name=${serv}><h4>/hurd/${serv}</h4></a>" >>/tmp/ServUsg.html
    echo "" >>/tmp/ServUsg.html; 
    echo "<PRE>" >>/tmp/ServUsg.html;
    /hurd/${serv} --help  >>/tmp/ServUsg.html 2>&1; 
    echo "</PRE>" >>/tmp/ServUsg.html;
    echo "" >>/tmp/ServUsg.html;
  done




#################################################
# End
#################################################
echo "    </body>" >>/tmp/ServUsg.html
echo "</HTML>" >>/tmp/ServUsg.html
